version: '2'
services:
  catalogueservice-app:
    image: catalogueservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://catalogueservice-postgresql:5432/catalogueservice
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  catalogueservice-postgresql:
    extends:
      file: postgresql.yml
      service: catalogueservice-postgresql
